#!/bin/bash
    if [ $1 = "clean" ]; then
        rm $2.o
        rm $2.lst
        rm $2
        clear
    else
        clear
        nasm -f elf -g -F dwarf -l $1.lst $1.asm 
        ld -m elf_i386 -s -o $1 $1.o
        ./$1
    fi